# Generated by Django 2.1.3 on 2018-11-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=1000)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('radius', models.IntegerField()),
                ('calculation', models.IntegerField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
