# Generated by Django 2.1.3 on 2018-11-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='calculation',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='result',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=50),
        ),
        migrations.AlterField(
            model_name='result',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=50),
        ),
    ]
